// javascript/reactjs-todo-start/client/components/journey/form.js
/*
 * forgerock-sample-web-react
 *
 * form.js
 *
 * Copyright (c) 2024 Ping Identity. All rights reserved.
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 */

import React, { Fragment, useEffect, useContext, useReducer } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';

import Boolean from './boolean';
import { DEBUGGER } from '../../constants';
import Alert from './alert';
import Choice from './choice';
import Kba from './kba';
import Loading from '../utilities/loading';
import Password from './password';
import treeReducer from './tree-reducer';
import useJourneyHandler from './journey-state';
import { AppContext } from '../../global-state';
import TermsConditions from './terms-conditions';
import Text from './text';
import Unknown from './unknown';
import Button from './button';
import TextOutput from './text-output';
import Confirmation from './confirmation';
import WebAuthn from './web-authn';
import KeyIcon from '../../components/icons/key-icon';
import NewUserIcon from '../../components/icons/new-user-icon';
import FingerPrintIcon from '../../components/icons/finger-print-icon';
import IdentityProvider from './identity-provider';

/** ***************************************************************************
 * SDK INTEGRATION POINT
 * ----------------------------------------------------------------------------
 * Details: Below, you will see the following settings:
 * Import the SDK you will need FRWebAuthn, WebAuthnStepType, FRAuth, CallbackType

 *************************************************************************** */

/**
 * @function Form - React component for managing the user authentication journey
 * @param {Object} props - props object from React
 * @param {Object} props.action - Action object for a "reducer" pattern
 * @param {string} props.action.type - Action type string that represents the action
 * @param {Object} props.followUp - A function that should be run after successful authentication
 * @param {Object} props.journey - Query param that represents the journey. Testing purposes
 * @returns {Object} - React component object
 */
export default function Form({ action, bottomMessage, followUp, topMessage, journey }) {
  /**
   * Compose the state used in this view.
   * First, we will use the global state methods found in the App Context.
   * Then, we will create local state to manage the login journey.
   *
   * The destructing of the hook's array results in index 0 having the state value,
   * and index 1 having the "setter" method to set new state values.
   */
  // Used for setting global authentication state
  const [state, methods] = useContext(AppContext);
  // Map action to form metadata: title, button text and tree
  const [form] = useReducer(treeReducer, treeReducer(null, action, journey));
  // Used for redirection after success
  const navigate = useNavigate();
  const [params] = useSearchParams();

  // Get the code and state from the URL query parameters
  const codeParam = params.get('code');
  const stateParam = params.get('state');

  let resumeUrl = '';
  if (codeParam && stateParam) {
    resumeUrl = window.location.href;
  }

  /**
   * Custom "hook" for handling form orchestration
   */
  const [
    { formFailureMessage, renderStep, submittingForm, user },
    { setSubmissionStep, setSubmittingForm },
  ] = useJourneyHandler({ action, form, resumeUrl });

  /**
   * If the user successfully authenticates, let React complete
   * rendering, then complete setting the state and redirect to home.
   */
  useEffect(() => {
    async function finalizeAuthState() {
      /**
       * First, let's see if we get a user back from useJourneyHandler.
       * If we do, let's set the user data and redirect back to home.
       */
      if (user) {
        /**
         * Set user state/info on "global state"
         */
        methods.setUser(user.name);
        methods.setEmail(user.email);
        methods.setAuthentication(true);

        // Run follow-up function if present
        followUp && (await followUp());

        // Redirect back to the home page
        navigate('/');
      }
    }

    finalizeAuthState();

    // Only `user` is a needed dependency, all others are "stable"
  }, [user]);

  /**
   * Iterate through callbacks received from AM and map the callback to the
   * appropriate callback component, pushing that component
   * the StepComponent's array.
   */
  function mapCallbacksToComponents(cb, idx) {
    const name = cb?.payload?.input?.[0].name;
    /** *********************************************************************
     * SDK INTEGRATION POINT
     * Summary:SDK callback method for getting the callback type
     * ----------------------------------------------------------------------
     * Details: This method is helpful in quickly identifying the callback
     * when iterating through an unknown list of AM callbacks
     ********************************************************************* */
    if (DEBUGGER) debugger;
    switch (cb.getType()) {
      // Fill in all the cases for the different callback types
      default:
        // If current callback is not supported, render a warning message
        return <Unknown callback={cb} key={`unknown-${idx}`} />;
    }
  }
  /**
   * Render conditions for presenting appropriate views to user.
   * First, we need to handle no "step", which means we are waiting for
   * the initial response from AM for authentication.
   *
   * Once we have a step, we then need to ensure we don't already have a
   * success or failure. If we have a step but don't have a success or
   * failure, we will likely have callbacks that we will need to present'
   * to the user in their render component form.
   */
  if (!renderStep) {
    /**
     * Since there is no step information we need to call AM to retrieve the
     * instructions for rendering the login form.
     */
    return <Loading message="Checking your session ..." />;
  } else if (renderStep.type === 'LoginSuccess') {
    /**
     * Since we have successfully authenticated, show a success message to
     * user while we complete the process and redirect to home page.
     */
    return <Loading message="Success! Redirecting ..." />;
  } else if (
    renderStep.type === 'Step' &&
    FRWebAuthn.getWebAuthnStepType(renderStep) !== WebAuthnStepType.None
  ) {
    return (
      <>
        <div className="cstm_form-icon align-self-center mb-3">
          <FingerPrintIcon size="72px" />
        </div>
        <WebAuthn step={renderStep} setSubmissionStep={setSubmissionStep} />
      </>
    );
  } else if (
    renderStep.type === 'Step' &&
    renderStep?.getCallbacksOfType(CallbackType.RedirectCallback).length > 0
  ) {
    FRAuth.redirect(renderStep);
    return <Loading message="Redirecting ..." />;
  } else if (renderStep.type === 'Step') {
    /**
     * The step to render has callbacks, so we need to collect additional
     * data from user. Map callbacks to form inputs.
     */
    return (
      <Fragment>
        <div className="cstm_form-icon  align-self-center mb-3">
          {action.type === 'login' ? <KeyIcon size="72px" /> : <NewUserIcon size="72px" />}
        </div>
        <h1 className={`text-center fs-2 mb-3 ${state.theme.textClass}`}>{form.titleText}</h1>
        {topMessage}
        <form
          className="cstm_form"
          onSubmit={(event) => {
            event.preventDefault();
            // Indicate form processing
            setSubmittingForm(true);
            // set currently rendered step as step to be submitted
            setSubmissionStep(renderStep);
          }}
        >
          {formFailureMessage ? <Alert message={formFailureMessage} type="error" /> : null}
          {
            /**
             * Map over the callbacks in renderStep and render the appropriate
             * component for each one.
             */
            renderStep.callbacks.map(mapCallbacksToComponents)
          }
          <Button buttonText={form.buttonText} submittingForm={submittingForm} />
        </form>
        {bottomMessage}
      </Fragment>
    );
  } else {
    /**
     * Just in case things blow up.
     */
    return <Alert message={renderStep.payload.message} type="error" />;
  }
}

// javascript/angular-todo-davinci/src/app/features/davinci/form/form.component.ts
/*
 * ping-sample-web-angular-davinci
 *
 * form.component.ts
 *
 * Copyright (c) 2025 Ping Identity Corporation. All rights reserved.
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 */
import { Component, OnInit, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';

import { TextInputComponent } from '../text-input/text-input.component';
import { PasswordComponent } from '../password/password.component';
import { SubmitButtonComponent } from '../submit-button/submit-button.component';
import { FlowButtonComponent } from '../flow-link/flow-link.component';
import { LoadingComponent } from '../../../utilities/loading/loading.component';
import { AlertComponent } from '../alert/alert.component';
import { UnknownComponent } from '../unknown/unknown.component';
import { KeyIconComponent } from '../../../icons/key-icon/key-icon.component';
import { NewUserIconComponent } from '../../../icons/new-user-icon/new-user-icon.component';

import { Collectors, DavinciClient, NodeStates } from '@forgerock/davinci-client/types';
import createClient from '../davinci.utils';
import { SdkService } from '../../../services/sdk.service';

@Component({
  selector: 'app-davinci-form',
  templateUrl: './form.component.html',
  standalone: true,
  imports: [
    FormsModule,
    TextInputComponent,
    PasswordComponent,
    SubmitButtonComponent,
    FlowButtonComponent,
    LoadingComponent,
    AlertComponent,
    UnknownComponent,
    KeyIconComponent,
    NewUserIconComponent,
  ],
})

/**
 * A form for managing the user authentication and authorization flow
 */
export class DavinciFormComponent implements OnInit {
  private readonly sdkService = inject(SdkService);
  private readonly router = inject(Router);

  /**
   * Create local state to manage the DaVinci flow
   */
  client: DavinciClient | null = null;
  node: NodeStates | null = null;
  collectors: Collectors[] = [];
  formName = '';
  formAction = '';
  errorMessage = '';
  isSubmittingForm = false;

  /**
   * @function renderForm - Set the form data for the DaVinci flow based on node status
   * @returns {void}
   */
  renderForm(): void {
    /**
     * Set the form collectors needed to compose the form
     */
    this.collectors = this.client?.getCollectors() ?? [];

    /**
     * Set any form details that should be displayed. Use the getClient() method to
     * conveniently get the client information from the node.
     */
    const clientInfo = this.client?.getClient(); // We don't have a type for ClientInfo yet
    switch (clientInfo?.status) {
      case 'continue':
        this.formName = clientInfo.name ?? '';
        this.formAction = clientInfo.action ?? '';
        break;
      case 'error':
        this.errorMessage = this.node?.error?.message ?? 'An unknown error occurred';
        break;
      case 'failure':
        this.errorMessage = 'An unknown failure occurred';
        break;
      default:
        return;
    }
  }

  /**
   * @function handleSuccess - Continue with authorization after successful login
   * @param {string} code - The authorization code from a successfully completed DaVinci flow
   * @param {string} state - The authorization state from a successfully completed DaVinci flow
   * @returns {Promise<void>}
   */
  private async successHandler(code: string, state: string): Promise<void> {
    /**
     * Upon successful login, pass the authorization code and state to the SDK
     * service to start the OIDC flow. Upon successfully retrieving a user profile,
     * redirect the user to the home page.
     */
    try {
      const user = await this.sdkService.startOidc({ code, state });
      user && this.router.navigateByUrl('/home');
    } catch (error) {
      console.error('Error handling success:', error);
      this.sdkService.isAuthenticated = false;
    }
  }

  /** *********************************************************************
   * SDK INTEGRATION POINT
   * Summary: Initialize the Davinci client and flow
   * ----------------------------------------------------------------------
   * Details: Start the DaVinci flow to get the first node for rendering
   * the form. If the user is already authenticated then skip to the OIDC
   * step otherwise render a form
   ********************************************************************* */
  async ngOnInit(): Promise<void> {
    try {
      if (!this.client || !this.node) {
        this.client = await createClient();
        this.node = (await this.client?.start()) ?? null;

        if (this.node?.status === 'success') {
          const code = this.node.client?.authorization?.code ?? '';
          const state = this.node.client?.authorization?.state ?? '';
          await this.successHandler(code, state);
        } else {
          this.renderForm();
        }
      }
    } catch (error) {
      console.error('Error initializing DaVinci: ', error);
    }
  }

  /**
   * @function submitHandler - The function to call when the form is submitted
   * @param {Object} event - The event object from the form submission
   * @returns {Promise<void>}
   */
  async submitHandler(event?: Event): Promise<void> {
    event?.preventDefault();
    this.isSubmittingForm = true;

    try {
      /** *********************************************************************
       * SDK INTEGRATION POINT
       * Summary: Submit the form and check the next node for next steps
       * ----------------------------------------------------------------------
       * Details: Get the next node in the flow from DaVinci. Notice there is
       * no need to pass the node with set values on collectors since the DaVinci
       * client will manage the state of the current node. Continue with the
       * authorization flow if it is a success node otherwise render another form.
       ********************************************************************* */
      this.node = (await this.client?.next()) ?? null;
      if (this.node?.status === 'success') {
        const code = this.node.client?.authorization?.code ?? '';
        const state = this.node.client?.authorization?.state ?? '';
        await this.successHandler(code, state);
      } else {
        this.renderForm();
      }
    } catch (error) {
      console.error('Error submitting form;', error);
    } finally {
      this.isSubmittingForm = false;
    }
  }
}

<!--
ping-sample-web-angular-davinci

form.component.html

Copyright (c) 2025 Ping Identity Corporation. All rights reserved.
This software may be modified and distributed under the terms
of the MIT license. See the LICENSE file for details.
-->

<!--
Render conditions for presenting appropriate views to user.
 First, we need to handle no "node", which means we are waiting for
 the initial response from PingOne for authentication.

 Once we have a node, we then need to ensure we don't already have a
 success or failure. If we have a node but don't have a success or
 failure, we will likely have collectors that we will need to present
 to the user in their render component form.
 -->

<form (submit)="submitHandler($event)">
  @if (formAction) {
    <div class="cstm_form-icon text-center mb-3">
      @switch (formAction) {
        @case ('SIGNON') {
          <app-key-icon size="72px" />
        }
        @case ('REGISTER') {
          <app-new-user-icon size="72px" />
        }
        @default {}
      }
    </div>
  }
  @if (!node || node.status === 'start') {
    <!--
    Since there is no node information we need to call DaVinci to retrieve the
      instructions for rendering the login form.
      -->
    <app-loading message="Checking your session..."></app-loading>
  } @else if (node.status === 'success') {
    <!--
    Since we have successfully authenticated, show a success message to
    user while we complete the process and redirect to home page.
    -->
    <app-alert type="success" message="Success! You're logged in."></app-alert>
  } @else if (node.status === 'continue' && collectors.length) {
    <!--
    The node to render has collectors, so we need to collect additional
    data from user.
    -->

    <h1 class="text-center fs-2 mb-3">{{ formName }}</h1>

    <!--
    Iterate over the collectors and render the appropriate
    component for each one.
    -->
    @for (collector of collectors; track collector) {
      @switch (collector.type) {
        @case ('TextCollector') {
          <app-text-input
            [key]="collector.output.key"
            [label]="collector.output.label"
            [update]="client?.update(collector)"
          />
        }
        @case ('PasswordCollector') {
          <app-password
            [key]="collector.output.key"
            [label]="collector.output.label"
            [update]="client?.update(collector)"
          />
        }
        @case ('SubmitCollector') {
          <app-submit-button
            [key]="collector.output.key"
            [label]="collector.output.label"
            [submittingForm]="isSubmittingForm"
          />
        }
        @case ('FlowCollector') {
          <app-flow-link
            [collector]="collector"
            [flow]="client?.flow({ action: collector.output.key })"
            (renderForm)="renderForm()"
          />
        }
        @default {
          <app-unknown [collector]="collector" />
        }
      }
    }
  } @else if (node.status === 'error' || node.status === 'failure') {
    <!--
    Something went wrong, show an error message to the user.
    -->
    <app-alert type="error" [message]="errorMessage" />
  } @else {
    <!--
    Just in case things blow up.
    -->
    <app-alert type="error" message="Unknown node status" />
  }
</form>
