// javascript/angular-todo-davinci/src/app/features/davinci-client/form/form.component.ts
/*
 * ping-sample-web-angular-davinci
 *
 * form.component.ts
 *
 * Copyright (c) 2025 Ping Identity Corporation. All rights reserved.
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 */
import { Component, OnInit, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';

import { ProtectComponent } from '../protect/protect.component';
import { TextInputComponent } from '../text-input/text-input.component';
import { PasswordComponent } from '../password/password.component';
import { SubmitButtonComponent } from '../submit-button/submit-button.component';
import { FlowButtonComponent } from '../flow-link/flow-link.component';
import { LoadingComponent } from '../../../utilities/loading/loading.component';
import { AlertComponent } from '../alert/alert.component';
import { UnknownComponent } from '../unknown/unknown.component';
import { KeyIconComponent } from '../../../icons/key-icon/key-icon.component';
import { NewUserIconComponent } from '../../../icons/new-user-icon/new-user-icon.component';

import { SuccessNode } from '@forgerock/davinci-client/types';
import { UserService } from '../../../services/user.service';
import { DavinciService } from '../../../services/davinci/davinci.service';
import { OAuthService } from '../../../services/oauth.service';

@Component({
  selector: 'app-davinci-form',
  templateUrl: './form.component.html',
  standalone: true,
  imports: [
    FormsModule,
    ProtectComponent,
    TextInputComponent,
    PasswordComponent,
    SubmitButtonComponent,
    FlowButtonComponent,
    LoadingComponent,
    AlertComponent,
    UnknownComponent,
    KeyIconComponent,
    NewUserIconComponent,
  ],
  providers: [DavinciService, OAuthService]
})

/**
 * A form for managing the user authentication and authorization flow
 */
export class DavinciFormComponent implements OnInit {
  readonly davinciService = inject(DavinciService);
  private readonly oauthService = inject(OAuthService);
  private readonly userService = inject(UserService);
  private readonly router = inject(Router);

  // Create local state for form metadata
  formName = '';
  formAction = '';
  errorMessage = '';
  isSubmittingForm = false;

  /**
   * @function setFormMeta - Set the form metadata for the DaVinci flow
   * @returns {void}
   */
  setFormMeta = (): void => {
    const clientInfo = this.davinciService.clientInfo;
    if (clientInfo?.status === 'continue' || clientInfo?.status === 'error') {
      this.formName = clientInfo.name ?? '';
      this.formAction = clientInfo.action ?? '';
    }

    const currentNode = this.davinciService.node;
    if (currentNode?.status === 'error') {
      this.errorMessage = currentNode?.error?.message ?? 'An unknown error occurred';
    }
}

  /** *********************************************************************
   * SDK INTEGRATION POINT
   * Summary: Initialize the Davinci client and flow
   * ----------------------------------------------------------------------
   * Details: Start the DaVinci flow to get the first node for rendering the form.
   ********************************************************************* */
  async ngOnInit(): Promise<void> {
    await this.davinciService.initDavinci();
    this.setFormMeta();

    // If the initial node is a success node, then skip to handling OAuth
    const initialNode = this.davinciService.node;
    console.log('intial node', initialNode);
    if (initialNode?.status === 'success') {
      await this.handleSuccess(initialNode);
    }
  }

  /**
   * @function hasProtectCollector - Determines if there is a Protect SDK collector
   * @param {Object} collectors - An array of collectors from DaVinci
   * @returns {boolean} - True if there is a Protect SDK collector otherwise false
   */
  hasProtectCollector(collectors) {
    return collectors?.some(
      (collector) => collector.type === 'TextCollector' && collector.name === 'protectsdk',
    );
  }

  /**
   * @function submitProtect - Handles Protect collector submission
   * @returns {Promise<void>}
   */
  submitProtectCallback = async (): Promise<void> => {
    await this.davinciService.setNext();
    this.setFormMeta();
  };

  /**
   * @function submitHandler - The function to call when the form is submitted
   * @param {Object} event - The event object from the form submission
   * @returns {Promise<void>}
   */
  async submitHandler(event: Event): Promise<void> {
    event.preventDefault();
    this.isSubmittingForm = true;

    try {
      /**
       * Get the next node in the flow and continue with authorization if
       * it is a success node
       */
      await this.davinciService.setNext();
      this.setFormMeta();

      const currentNode = this.davinciService.node;
      if (currentNode?.status === 'success') {
        await this.handleSuccess(currentNode);
      }
    } catch (error) {
      console.error(error);
    } finally {
      this.isSubmittingForm = false;
    }
  }


  /**
   * @function finalizeAuthState - Update global state in the UserService
   * @param {Record<string, string>} user - A user from the JS SDK
   * @returns {void}
   */
    private finalizeAuthState(user: Record<string, string>): void {
      this.userService.username = `${user.given_name ?? ''} ${user.family_name ?? ''}`;
      this.userService.email = user.email ?? '';
      this.userService.isAuthenticated = true;
    }

  /**
   * @function handleSuccess - Continue with authorization after successful login
   * @param {SuccessNode} node - A success node from the DaVinci flow
   * @returns {Promise<void>}
   */
  private async handleSuccess(successNode: SuccessNode): Promise<void> {
    /**
     * Upon successful login, pass the authorization code and state to the OAuth
     * service to get an authenticated user. Then, set the global user state in
     * the UserService and finish by redirecting to the home page.
     */
    try {
      const code = successNode.client?.authorization?.code ?? '';
      const state = successNode.client?.authorization?.state ?? '';
      const user = await this.oauthService.handleOAuth({ code, state });
      if (user) {
        this.finalizeAuthState(user as Record<string, string>);

        // Redirect back to the home page
        this.router.navigateByUrl('/home');
      } else {
        this.userService.isAuthenticated = false;
      }
    } catch (error) {
      console.error('Error handling success:', error);
      this.userService.isAuthenticated = false;
    }
  }
}

<!--
ping-sample-web-angular-davinci

form.component.html

Copyright (c) 2025 Ping Identity Corporation. All rights reserved.
This software may be modified and distributed under the terms
of the MIT license. See the LICENSE file for details.
-->

<!-- 
Render conditions for presenting appropriate views to user.
 First, we need to handle no "node", which means we are waiting for
 the initial response from PingOne for authentication.

 Once we have a node, we then need to ensure we don't already have a
 success or failure. If we have a node but don't have a success or
 failure, we will likely have collectors that we will need to present
 to the user in their render component form. 
 -->

<form (submit)="submitHandler($event)">
  @if (formAction()) {
    <div class="cstm_form-icon text-center mb-3">
      @switch (formAction()) {
        @case ('SIGNON') {
          <app-key-icon size="72px" />
        }
        @case ('REGISTER') {
          <app-new-user-icon size="72px" />
        }
        @default {}
      }
    </div>
  }
  @if (!node() || node().status === 'start') {
    <!-- 
    Since there is no node information we need to call DaVinci to retrieve the
      instructions for rendering the login form. 
      -->
    <app-loading message="Checking your session..."></app-loading>
  } @else if (node().status === 'success') {
    <!-- 
    Since we have successfully authenticated, show a success message to
    user while we complete the process and redirect to home page.
    -->
    <app-alert type="success" message="Success! You're logged in."></app-alert>
  } @else if (node().status === 'continue' && collectors().length) {
    <!-- 
    The node to render has collectors, so we need to collect additional
    data from user.
    -->
    @if (formName() && !hasProtectCollector(collectors())) {
      <h1 class="text-center fs-2 mb-3">{{ formName() }}</h1>
    }

    <!-- 
    Iterate over the collectors and render the appropriate
    component for each one.
    -->
    @for (collector of collectors(); track collector) {
      @if (collector.type === 'TextCollector' && collector.name === 'protectsdk') {
        <app-protect
          [label]="collector.output.label"
          [update]="updater()(collector)"
          [submitProtect]="submitProtectCallback"
        />
      } @else {
        @switch (collector.type) {
          @case ('TextCollector') {
            <app-text-input
              [key]="collector.output.key"
              [label]="collector.output.label"
              [update]="updater()(collector)"
            />
          }
          @case ('PasswordCollector') {
            <app-password
              [key]="collector.output.key"
              [label]="collector.output.label"
              [update]="updater()(collector)"
            />
          }
          @case ('SubmitCollector') {
            <app-submit-button
              [key]="collector.output.key"
              [label]="collector.output.label"
              [submittingForm]="isSubmittingForm"
            />
          }
          @case ('FlowCollector') {
            <app-flow-link [collector]="collector" [startNewFlow]="startNewFlow" />
          }
          @default {
            <app-unknown [collector]="collector" />
          }
        }
      }
    }
  } @else if (node().status === 'error') {
    <!-- 
    Something went wrong, show an error message to the user.
    -->
    <app-alert type="error" [message]="errorMessage()" />
  } @else {
    <!-- 
    Just in case things blow up.
    -->
    <app-alert type="error" message="Unknown node status" />
  }
</form>

// javascript/reactjs-todo-davinci/client/components/davinci-client/form.js
/*
 * ping-sample-web-react-davinci
 *
 * form.js
 *
 * Copyright (c) 2025 Ping Identity Corporation. All rights reserved.
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 */
import React, { Fragment, useContext, useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import Readonly from './readonly.js';
import Text from './text.js';
import Error from './error.js';
import Password from './password.js';
import SubmitButton from './submit-button.js';
import Protect from './protect.js';
import ObjectValueComponent from './object-value.js';
import SingleSelect from './single-select.js';
import FlowLink from './flow-link.js';
import Unknown from './unknown.js';
import Alert from './alert.js';
import KeyIcon from '../icons/key-icon';
import NewUserIcon from '../icons/new-user-icon';
import Loading from '../utilities/loading.js';
import { AppContext } from '../../global-state.js';
import useDavinci from './hooks/davinci.hook.js';
import useOAuth from './hooks/oauth.hook.js';

/**
 * @function Form - React view for managing the user authentication journey
 * @returns {Object} - React component object
 */
export default function Form() {
  /**
   * Compose the state used in this view.
   * First, we will use the global state methods found in the App Context.
   * Then, we will create local state to manage the login flow.
   *
   * The destructing of the hook's array results in index 0 having the state value,
   * and index 1 having the "setter" methods to set new state values.
   */

  const [{ theme }, methods] = useContext(AppContext);
  const [isLoading, setIsLoading] = useState(false);
  const navigate = useNavigate();

  /**
   * Custom hooks for managing form state and authorization
   */
  const [user, setCode] = useOAuth();
  const [{ formName, formAction, node, collectors }, { getError, setNext, startNewFlow, updater }] =
    useDavinci();

  /**
   * @function hasProtectCollector - Determines if there is a Protect SDK collector
   * @param {Object} collectors - An array of collectors from DaVinci
   * @returns {boolean} - True if there is a Protect SDK collector otherwise false
   */
  function hasProtectCollector(collectors) {
    return collectors?.some(
      (collector) => collector.type === 'TextCollector' && collector.name === 'protectsdk',
    );
  }

  /**
   * @function submitProtect - Handles Protect collector submission
   * @returns {Promise<void>}
   */
  async function submitProtect() {
    await setNext();
  }

  /**
   * Upon successful login, set the authorization code and state used in the custom
   * useOAuth hook to start the OAuth process.
   */
  useEffect(() => {
    async function setOAuthCode() {
      if (node?.status === 'success') {
        const code = node.client?.authorization?.code;
        const state = node.client?.authorization?.state;
        setCode({ code, state });
      }
    }

    setOAuthCode();
  }, [node?.status]);

  /**
   * If the user successfully authenticates, let React complete
   * rendering, then complete setting the global state and redirect to home.
   */
  useEffect(() => {
    async function finalizeAuthState() {
      /**
       * First, let's see if we get a user back from useOauth.
       * If we do, let's set the user data and redirect back to home.
       */
      if (user) {
        /**
         * Set user state/info on "global state"
         */
        methods.setUser(`${user.given_name ?? ''} ${user.family_name ?? ''}`);
        methods.setEmail(user.email);
        methods.setAuthentication(true);

        // Redirect back to the home page
        navigate('/');
      }
    }

    finalizeAuthState();
  }, [user]);

  /**
   * @function onSubmitHandler - The function to call when the form is submitted
   * @param {Object} event - The event object from the form submission
   * @returns {undefined}
   */
  async function onSubmitHandler(event) {
    event.preventDefault();
    setIsLoading(true);

    try {
      // Get the next node in the flow
      await setNext();
    } catch (error) {
      console.error(error);
    } finally {
      setIsLoading(false);
    }
  }

  /**
   * Iterate through collectors received from DaVinci and map the collector to the
   * appropriate collector component
   */
  function mapCollectorsToComponents(collector, idx) {
    /** *********************************************************************
     * SDK INTEGRATION POINT
     * Summary: SDK callback method for getting the collector type
     * ----------------------------------------------------------------------
     * Details: This method is helpful in quickly identifying the collector
     * when iterating through an unknown list of Davinci collectors
     ********************************************************************* */
    const collectorName = collector.name;

    if (collector.type === 'TextCollector' && collector.name === 'protectsdk') {
      return <Protect updater={updater(collector)} submit={submitProtect} key={collectorName} />;
    }

    switch (collector.type) {
      case 'TextCollector':
        return (
          <Text
            collector={collector}
            inputName={collectorName}
            updater={updater(collector)}
            key={collectorName}
          />
        );
      case 'PasswordCollector':
        return (
          <Password
            collector={collector}
            inputName={collectorName}
            updater={updater(collector)}
            key={collectorName}
          />
        );
      case 'SingleSelectCollector':
        return (
          <SingleSelect collector={collector} updater={updater(collector)} key={collectorName} />
        );
      case 'ERROR_DISPLAY':
        return <Error key={idx + 'err'} getError={getError} />;
      case 'ReadOnlyCollector':
        return <Readonly key={idx + collectorName} collector={collector} />;
      case 'PhoneNumberCollector':
      case 'DeviceRegistrationCollector':
      case 'DeviceAuthenticationCollector':
        return (
          <ObjectValueComponent
            inputName={collectorName}
            collector={collector}
            updater={updater(collector)}
            key={collectorName}
            submitForm={setNext}
          />
        );
      case 'PROTECT':
        return <Protect updater={updater(collector)} key={collectorName} />;
      case 'SubmitCollector':
        return <SubmitButton collector={collector} isLoading={isLoading} key={collectorName} />;
      case 'FlowCollector':
        return <FlowLink collector={collector} startNewFlow={startNewFlow} key={collectorName} />;
      default:
        // If current collector is not supported, render a warning message
        return <Unknown collector={collector} key={`unknown-${idx}`} />;
    }
  }

  /**
   * @function formIcon - Gets the appropriate icon for the form
   * @param {string} formAction - The type of form
   * @returns {Object} - React icon component
   */
  function formIcon(formAction) {
    switch (formAction) {
      case 'SIGNON':
        return <KeyIcon size="72px" />;
      case 'REGISTER':
        return <NewUserIcon size="72px" />;
      default:
        return null;
    }
  }

  /**
   * Render conditions for presenting appropriate views to user.
   * First, we need to handle no "node", which means we are waiting for
   * the initial response from PingOne for authentication.
   *
   * Once we have a node, we then need to ensure we don't already have a
   * success or failure. If we have a node but don't have a success or
   * failure, we will likely have collectors that we will need to present
   * to the user in their render component form.
   */
  if (!node || node.status === 'start') {
    /**
     * Since there is no node information we need to call DaVinci to retrieve the
     * instructions for rendering the login form.
     */
    return <Loading message="Checking your session ..." />;
  } else if (node.status === 'success') {
    /**
     * Since we have successfully authenticated, show a success message to
     * user while we complete the process and redirect to home page.
     */
    return <Alert message="Success! You're logged in." type="success" />;
  } else if (node.status === 'continue') {
    /**
     * The node to render has collectors, so we need to collect additional
     * data from user.
     */
    return (
      <Fragment>
        <div className="cstm_form-icon  align-self-center mb-3">{formIcon(formAction)}</div>
        <h1 className={`text-center fs-2 mb-3 ${theme.textClass}`}>
          {hasProtectCollector(collectors) ? '' : formName}
        </h1>
        {/*
         * Map over the collectors and render the appropriate
         * component for each one.
         * */}
        <form onSubmit={onSubmitHandler}>{collectors?.map(mapCollectorsToComponents)}</form>
      </Fragment>
    );
  } else if (node.status === 'error') {
    /**
     * Something went wrong, show an error message to the user.
     */
    return <Alert type="error" message={node.error.message} />;
  } else {
    /**
     * Just in case things blow up.
     */
    return <Alert type="error" message="Unknown node status" />;
  }
}
