// javascript/reactjs-todo-davinci/client/components/davinci-client/password.js
/*
 * ping-sample-web-react-davinci
 *
 * password.js
 *
 * Copyright (c) 2025 - 2026 Ping Identity Corporation. All rights reserved.
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 */
import React, { useState, useContext } from 'react';
import { ThemeContext } from '../../context/theme.context.js';
import EyeIcon from '../icons/eye-icon';

const Password = ({ collector, inputName, updater }) => {
  const theme = useContext(ThemeContext);
  const [isVisible, setVisibility] = useState(false);
  const passwordLabel = collector.output.label;

  /**
   * @function toggleVisibility - toggles the password from masked to plaintext
   */
  function toggleVisibility() {
    setVisibility(!isVisible);
  }

  return (
    <div className="cstm_form-floating input-group form-floating mb-3">
      <input
        className={`cstm_input-password form-control border-end-0 bg-transparent ${theme.textClass} ${theme.borderClass}`}
        id={inputName}
        name={inputName}
        type={isVisible ? 'text' : 'password'}
        onChange={(e) => updater(e.target.value)}
      />
      <label htmlFor={inputName}>{passwordLabel}</label>
      <button
        className={`cstm_input-icon border-start-0 input-group-text bg-transparent ${theme.textClass} ${theme.borderClass}`}
        onClick={toggleVisibility}
        type="button"
      >
        <EyeIcon visible={isVisible} />
      </button>
    </div>
  );
};

export default Password;

// javascript/angular-todo-davinci/src/app/features/davinci/password/password.component.ts
/*
 * ping-sample-web-angular-davinci
 *
 * password.component.ts
 *
 * Copyright (c) 2025 Ping Identity Corporation. All rights reserved.
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 */

import { Component, Input } from '@angular/core';
import { EyeIconComponent } from '../../../icons/eye-icon/eye-icon.component';

@Component({
  selector: 'app-password',
  templateUrl: './password.component.html',
  standalone: true,
  imports: [EyeIconComponent],
})
export class PasswordComponent {
  @Input() key: string;
  @Input() label: string;
  @Input() update: (value: string) => void;

  isVisible = false;

  toggleVisibility(): void {
    this.isVisible = !this.isVisible;
  }

  onBlur(event: Event): void {
    this.update((event.target as HTMLInputElement).value);
  }
}
