// javascript/angular-todo-davinci/src/app/layout/footer/footer.component.ts
/*
 * ping-sample-web-angular-davinci
 *
 * footer.component.ts
 *
 * Copyright (c) 2025 Ping Identity Corporation. All rights reserved.
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 */

import { Component } from '@angular/core';

@Component({
  selector: 'app-footer',
  templateUrl: './footer.component.html',
  standalone: true,
})
export class FooterComponent {}

<!--
ping-sample-web-angular-davinci

footer.component.html

Copyright (c) 2025 Ping Identity Corporation. All rights reserved.
This software may be modified and distributed under the terms
of the MIT license. See the LICENSE file for details.
-->

<div class="cstm_container container-fluid">
  <small class="border-top d-block mt-5 py-5">
    The Angular name and logomark are properties of
    <a href="http://angular.io/license">Google LLC</a>, and their use herein is for learning and
    illustrative purposes only.
  </small>
</div>

// javascript/react-journey/client/components/layout/footer.js
/*
 * ping-sample-web-react-journey
 *
 * footer.js
 *
 * Copyright (c) 2026 Ping Identity Ping Identity Corporation. All rights reserved.
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 */

import React, { useContext } from 'react';

import { ThemeContext } from '../../context/theme.context';

/**
 * @function Footer - Footer React component
 * @returns {Object} - React component object
 */
export default function Footer() {
  const theme = useContext(ThemeContext);

  return (
    <div className="cstm_container container-fluid">
      <small
        className={`border-top d-block mt-5 py-5 ${theme.textClass} ${theme.borderHighContrastClass}`}
      >
        The React name and logomark are properties of <a href="https://reactjs.org">Facebook</a>,
        and their use herein is for learning and illustrative purposes only.
      </small>
    </div>
  );
}
