// javascript/angular-todo-davinci/src/app/layout/header/header.component.ts
/*
 * ping-sample-web-angular-davinci
 *
 * header.component.ts
 *
 * Copyright (c) 2025 Ping Identity Corporation. All rights reserved.
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 */

import { Component, inject } from '@angular/core';
import { Router, RouterLink } from '@angular/router';
import { UserService } from '../../services/user.service';
import { NgClass } from '@angular/common';
import { PingIconComponent } from '../../icons/ping-icon/ping-icon.component';
import { AngularIconComponent } from '../../icons/angular-icon/angular-icon.component';
import { HomeIconComponent } from '../../icons/home-icon/home-icon.component';
import { TodosIconComponent } from '../../icons/todos-icon/todos-icon.component';
import { AccountIconComponent } from '../../icons/account-icon/account-icon.component';

/**
 * Used to show a navigation bar with router links and user info
 */
@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  standalone: true,
  imports: [
    RouterLink,
    NgClass,
    PingIconComponent,
    AngularIconComponent,
    HomeIconComponent,
    TodosIconComponent,
    AccountIconComponent,
  ],
})
export class HeaderComponent {
  private readonly routerService = inject(Router);
  private readonly userService = inject(UserService);

  router = this.routerService;
  isAuthenticated = this.userService.isAuthenticated;
  username = this.userService.username;
  email = this.userService.email;
}

<!--
angular-todo-prototype

header.component.html

Copyright (c) 2021 ForgeRock. All rights reserved.
This software may be modified and distributed under the terms
of the MIT license. See the LICENSE file for details.
-->

<nav class="navbar navbar-expand navbar-light bg-white py-0 border-bottom">
  <div class="cstm_container container-fluid d-flex align-items-stretch">
    <a
      [routerLink]="'/'"
      class="cstm_navbar-brand navbar-brand py-3 pe-4 me-4"
      [ngClass]="{
        'cstm_navbar-brand_auth d-none d-sm-none d-md-block': userService.isAuthenticated
      }"
    >
      <app-forgerock-icon size="31px"></app-forgerock-icon> +
      <app-angular-icon size="40px"></app-angular-icon>
    </a>
    <div class="navbar-collapse d-flex align-items-stretch" id="navbarNav">
      <!--
        Show simple navigation with login / register links, or links relevant to current route
      -->
      <ng-container [ngTemplateOutlet]="userService.info ? navigation : login">
        <ng-template #navigation>
          <!--
            Show navigation links relevant to the current route
          -->
          <ul class="navbar-nav d-flex align-items-stretch me-auto">
            <li
              key="home"
              class="cstm_nav-item nav-item mx-1"
              [ngClass]="{
                'cstm_nav-item_active': router.url === '/' || router.url === '/home'
              }"
            >
              <a
                class="cstm_nav-link nav-link d-flex align-items-center h-100 p-0 ps-1"
                [routerLink]="'/home'"
              >
                <app-home-icon></app-home-icon>
                <span class="px-2 fs-6">Home</span>
              </a>
            </li>
            <li
              key="todos"
              class="cstm_nav-item nav-item mx-1"
              [ngClass]="{ 'cstm_nav-item_active': router.url === '/todos' }"
            >
              <a
                class="cstm_nav-link nav-link d-flex align-items-center h-100 p-0 ps-2"
                [routerLink]="'/todos'"
              >
                <app-todos-icon></app-todos-icon>
                <span class="px-2 fs-6">Todos</span>
              </a>
            </li>
          </ul>

          <div class="d-flex align-items-center">
            <div class="dropdown text-end">
              <button
                aria-expanded="false"
                class="btn h-auto p-0"
                data-bs-toggle="dropdown"
                id="account_dropdown"
              >
                <app-account-icon size="48px"></app-account-icon>
              </button>
              <ul
                class="dropdown-menu dropdown-menu-end shadow-sm pb-0"
                aria-labelledby="account_dropdown"
              >
                <!--
                  Show user info from user service
                -->
                <li>
                  <div class="dropdown-header border-bottom">
                    <p class="fw-bold fs-6 mb-0 text-dark">
                      {{ userService.info.name }}
                    </p>
                    <p class="mb-2">{{ userService.info.email }}</p>
                  </div>
                </li>
                <li>
                  <a class="dropdown-item py-2" [routerLink]="'/logout'"> Sign Out </a>
                </li>
              </ul>
            </div>
          </div>
        </ng-template>

        <ng-template #login>
          <ul class="navbar-nav d-flex align-items-stretch me-auto"></ul>
          <div class="d-flex py-3">
            <a
              [routerLink]="'/login'"
              class="cstm_login-link py-2 px-3 mx-1"
            >
              Sign In
            </a>
          </div>
        </ng-template>
      </ng-container>
    </div>
  </div>
</nav>

// javascript/react-journey/client/components/layout/header.js
/*
 * ping-sample-web-react-journey
 *
 * header.js
 *
 * Copyright (c) 2026 Ping Identity Corporation. All rights reserved.
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 */

import React, { useContext } from 'react';
import { Link, useLocation, useSearchParams } from 'react-router-dom';

import AccountIcon from '../icons/account-icon';
import ForgeRockIcon from '../icons/forgerock-icon';
import HomeIcon from '../icons/home-icon';
import ReactIcon from '../icons/react-icon';
import TodosIcon from '../icons/todos-icon';
import { OidcContext } from '../../context/oidc.context';
import { ThemeContext } from '../../context/theme.context';

/**
 * @function Header - Header React view
 * @returns {Object} - React component object
 */
export default function Header() {
  /**
   * Collects the global state for detecting user auth for rendering
   * appropriate navigational items.
   * The destructing of the hook's array results in index 0 having the state value,
   * and index 1 having the "setter" method to set new state values.
   */
  const [state] = useContext(OidcContext);
  const theme = useContext(ThemeContext);
  const location = useLocation();
  const [queryParams] = useSearchParams();

  const urlQueryParams = {
    pathname: '/login',
    search: queryParams.toString(),
  };

  let TodosItem;
  let LoginOrOutItem;

  /**
   * Render different navigational items depending on authenticated status
   */
  if (state.isAuthenticated) {
    TodosItem = [
      <li
        key="home"
        className={`cstm_nav-item ${
          location.pathname === '/' ? 'cstm_nav-item_active' : ''
        } nav-item mx-1`}
      >
        <Link className="cstm_nav-link nav-link d-flex align-items-center h-100 p-0 ps-1" to="/">
          <HomeIcon />
          <span className="px-2 fs-6">Home</span>
        </Link>
      </li>,
      <li
        key="todos"
        className={`cstm_nav-item ${
          location.pathname === '/todos' ? 'cstm_nav-item_active' : ''
        } nav-item`}
      >
        <Link
          className="cstm_nav-link nav-link d-flex align-items-center h-100 p-0 ps-2"
          to="/todos"
        >
          <TodosIcon />
          <span className="px-2 fs-6">Todos</span>
        </Link>
      </li>,
    ];
    LoginOrOutItem = (
      <div className="d-flex align-items-center">
        <div className="dropdown text-end">
          <button
            aria-expanded="false"
            className="btn h-auto p-0"
            data-bs-toggle="dropdown"
            id="account_dropdown"
          >
            <AccountIcon classes="cstm_profile-icon" size="48px" />
          </button>
          <ul
            className={`dropdown-menu dropdown-menu-end shadow-sm pb-0 ${theme.dropdownClass}`}
            aria-labelledby="account_dropdown"
          >
            <li>
              <div className={`dropdown-header border-bottom ${theme.borderClass}`}>
                <p
                  className={`fw-bold fs-6 mb-0 ${theme.textClass ? theme.textClass : 'text-dark'}`}
                >
                  {state.username}
                </p>
                <p className="mb-2">{state.email}</p>
              </div>
            </li>
            <li>
              <Link className="dropdown-item py-2" to="/logout">
                Sign Out
              </Link>
            </li>
          </ul>
        </div>
      </div>
    );
  } else {
    TodosItem = null;
    LoginOrOutItem = (
      <div className="d-flex py-3">
        <Link
          className={`cstm_login-link py-2 px-3 mx-1 ${
            theme.mode === 'dark' ? 'cstm_login-link_dark' : ''
          }`}
          to={urlQueryParams}
        >
          Sign In
        </Link>
        <Link className="btn btn-primary" to="/register">
          Sign Up
        </Link>
      </div>
    );
  }

  return (
    <nav
      className={`navbar navbar-expand ${theme.navbarClass} ${theme.borderHighContrastClass} py-0 border-bottom`}
    >
      <div className="cstm_container container-fluid d-flex align-items-stretch">
        <Link
          to="/"
          className={`cstm_navbar-brand ${
            state.isAuthenticated ? 'cstm_navbar-brand_auth' : ''
          } navbar-brand ${
            state.isAuthenticated ? 'd-none d-sm-none d-md-block' : ''
          } py-3 pe-4 me-4 ${theme.borderHighContrastClass}`}
        >
          <ForgeRockIcon size="31px" /> + <ReactIcon size="38px" />
        </Link>
        <div className="navbar-collapse d-flex align-items-stretch" id="navbarNav">
          <ul className="navbar-nav d-flex align-items-stretch me-auto">{TodosItem}</ul>
          {LoginOrOutItem}
        </div>
      </div>
    </nav>
  );
}
