// reactjs-todo-dv/client/components/davinci-client/submit-button.js
/*
 * forgerock-sample-web-react
 *
 * submit-button.js
 *
 * Copyright (c) 2021 ForgeRock. All rights reserved.
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 */
import React from 'react';

export default function SubmitButton({ collector }) {
  return (
    <button
      type="submit"
      className="btn btn-primary w-100 mb-2"
      value={collector.output.key}
      key={collector.output.key}
    >
      <span>{collector.output.label}</span>
    </button>
  );
}

// javascript/Archived/angular-todo-davinci/src/app/features/davinci/submit-button/submit-button.component.ts
/*
 * ping-sample-web-angular-davinci
 *
 * submit-button.component.ts
 *
 * Copyright (c) 2025 Ping Identity Corporation. All rights reserved.
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 */

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-submit-button',
  templateUrl: './submit-button.component.html',
  standalone: true,
  imports: [],
})
export class SubmitButtonComponent {
  @Input() key: string = '';
  @Input() label: string = '';
  @Input() submittingForm: boolean = false;
}
