// javascript/angular-todo-davinci/src/app/views/login/login.component.ts
/*
 * angular-todo-prototype
 *
 * login.component.ts
 *
 * Copyright (c) 2021 ForgeRock. All rights reserved.
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 */

import { Component } from '@angular/core';
import { BackHomeComponent } from '../../utilities/back-home/back-home.component';

import { DavinciFormComponent } from '../../features/davinci-client/form/form.component';

/**
 * Used to show a login page
 */
@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  standalone: true,
  imports: [BackHomeComponent, DavinciFormComponent],
})
export class LoginComponent {}

<!--
angular-todo-prototype

login.component.html

Copyright (c) 2021 ForgeRock. All rights reserved.
This software may be modified and distributed under the terms
of the MIT license. See the LICENSE file for details.
-->

<div class="cstm_container_v-centered container-fluid d-flex align-items-center">
  <div class="w-100">
    <app-back-home></app-back-home>
    <div class="card shadow-sm p-5 mb-2 w-100">
      <app-davinci-form></app-davinci-form>
    </div>
  </div>
</div>

// reactjs-todo-dv/client/views/login.js
/*
 * forgerock-sample-web-react
 *
 * login.js
 *
 * Copyright (c) 2021 ForgeRock. All rights reserved.
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 */
import React, { useContext } from 'react';
import BackHome from '../components/utilities/back-home';
import Card from '../components/layout/card';
import { useNavigate } from 'react-router-dom';
import DaVinciFlow from '../components/davinci-client/davinci-flow.js';
import { AppContext } from '../global-state.js';

/**
 * @function Login - React view for Login
 * @returns {Object} - React component object
 */
export default function Login() {
  const [state] = useContext(AppContext);
  // Used for redirection after success
  const navigate = useNavigate();
  // This function is passed to DaVinciFlow to be called when the flow is complete
  // Each individual flow might have a different completion action
  function onComplete() {
    navigate('/');
  }

  return (
    <div className="cstm_container_v-centered container-fluid d-flex align-items-center">
      <div className="w-100">
        <BackHome />
        <Card>
          <DaVinciFlow davinciClient={state.client} flowCompleteCb={onComplete} />
        </Card>
      </div>
    </div>
  );
}
