// angular-todo-dv/src/app/features/davinci-client/davinci-flow/davinci-flow.component.ts
/*
 * angular-todo-prototype
 *
 * davinci-flow.component.ts
 *
 * Copyright (c) 2021 ForgeRock. All rights reserved.
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 */
import { Component, EventEmitter, OnInit, Output } from '@angular/core';
import { TokenManager } from '@forgerock/javascript-sdk';
import { UserService } from '../../../services/user.service';

interface Collector {
  category: string;
  id: string;
  name: string;
  type: string;
  input?: {
    key: string;
    value: string;
    type: string;
  };
  output: {
    key: string;
    label: string;
    type: string;
    url?: string;
  };
}

@Component({
  selector: 'app-davinci-flow',
  templateUrl: './davinci-flow.component.html',
})
export class DaVinciFlowComponent implements OnInit {
  @Output() flowComplete = new EventEmitter<void>();

  // TODO: Get proper typings and delete this and the next line
  /* eslint-disable @typescript-eslint/no-explicit-any */

  davinciClient: any;
  isSubmittingForm = false;
  collectors: Collector[] = [];
  pageHeader = '';
  errorMessage = '';

  constructor(private readonly userService: UserService) {}

  async ngOnInit(): Promise<void> {
    this.davinciClient = this.userService.loginClient;
    const node = await this.davinciClient.start();

    if (node.status !== 'success') {
      this.renderForm(node);
    } else {
      this.completeFlow();
    }
  }

  updateValue(value: string, collector: Collector): void {
    const updater = this.davinciClient.update(collector);
    updater(value);
  }

  async submitHandler(event: Event): Promise<void> {
    event.preventDefault();
    this.isSubmittingForm = true;

    const nextNode = await this.davinciClient.next();
    this.mapRenderer(nextNode);
  }

  async completeFlow(): Promise<void> {
    const clientInfo = this.davinciClient.getClient();

    let code = '';
    let state = '';

    if (clientInfo?.status === 'success') {
      code = clientInfo.authorization?.code || '';
      state = clientInfo.authorization?.state || '';
    }

    await TokenManager.getTokens({ query: { code, state } });

    await this.userService.populateUserInfo();
    this.flowComplete.emit();
  }

  async renderForm(nextNode: any): Promise<void> {
    // Set h1 header
    this.pageHeader = nextNode.client?.name || '';
    const collectors = this.davinciClient.getCollectors();
    // Save collectors to state
    this.collectors = collectors;

    // If node is a protect node, move to next node without user interaction
    if (collectors.find((collector) => collector.name === 'protectsdk')) {
      const nextNode = await this.davinciClient.next();
      this.mapRenderer(nextNode);
    }
  }

  async onFlowButtonClicked(collector: Collector) {
    const flow = this.davinciClient.flow({ action: collector.output.key });
    const node = await flow(collector.output.key);
    this.renderForm(node);
  }

  mapRenderer(nextNode: any): void {
    this.isSubmittingForm = false;
    if (nextNode.status === 'next') {
      this.renderForm(nextNode);
    } else if (nextNode.status === 'success') {
      this.completeFlow();
    } else if (nextNode.status === 'error') {
      this.errorMessage = nextNode.error.message;
    } else {
      console.error('Unknown node status', nextNode);
    }
  }
}

<!--
angular-todo-prototype

davinci-flow.component.html

Copyright (c) 2021 ForgeRock. All rights reserved.
This software may be modified and distributed under the terms
of the MIT license. See the LICENSE file for details.
-->
<form (submit)="submitHandler($event)">
  <h2 *ngIf="pageHeader">{{ pageHeader }}</h2>
  <app-error-message *ngIf="errorMessage" [message]="errorMessage" />
  <ng-container *ngIf="collectors.length">
    <ng-container *ngFor="let collector of collectors">
      <app-protect
        *ngIf="collector.type === 'TextCollector' && collector.name === 'protectsdk'"
        [label]="collector.output.label"
        (protectProfile)="updateCollector(davinciClient.update(collector), $event)"
      />
      <app-text-input
        *ngIf="collector.type === 'TextCollector' && collector.name !== 'protectsdk'"
        [key]="collector.output.key"
        [label]="collector.output.label"
        (valueUpdated)="updateCollector(davinciClient.update(collector), $event)"
      />
      <app-password
        *ngIf="collector.type === 'PasswordCollector'"
        [key]="collector.output.key"
        [label]="collector.output.label"
        (valueUpdated)="updateCollector(davinciClient.update(collector), $event)"
      />
      <app-submit-button
        *ngIf="collector.type === 'SubmitCollector'"
        [key]="collector.output.key"
        [label]="collector.output.label"
        [submittingForm]="isSubmittingForm"
      />
      <app-flow-button
        *ngIf="collector.type === 'FlowCollector'"
        [label]="collector.output.label"
        (clicked)="onFlowButtonClicked(collector)"
      />
    </ng-container>
  </ng-container>
</form>

// reactjs-todo-dv/client/components/davinci-client/davinci-flow.js
/*
 * forgerock-sample-web-react
 *
 * davinci-flow.js
 *
 * Copyright (c) 2021 ForgeRock. All rights reserved.
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 */
import React, { useContext, useEffect, useState, useRef } from 'react';
import { TokenManager, UserManager } from '@forgerock/javascript-sdk';

import TextInput from './text-input.js';
import Password from './password.js';
import SubmitButton from './submit-button.js';
import Protect from './protect.js';
import FlowButton from './flow-button.js';
import ErrorMessage from './error-message.js';
import { AppContext } from '../../global-state.js';

/**
 * @function DaVinciFlow - React view for a DaVinci flow
 * @returns {Object} - React component object
 */
export default function DaVinciFlow({ davinciClient, flowCompleteCb }) {
  /**
   * Collects the global state for detecting user auth for rendering
   * appropriate navigational items.
   * The destructing of the hook's array results in index 0 having the state value,
   * and index 1 having the "setter" method to set new state values.
   */
  const [, methods] = useContext(AppContext);
  const [collectors, setCollectors] = useState([]);
  const [pageHeader, setPageHeader] = useState('');
  const [isSubmittingForm, setIsSubmittingForm] = useState(false);
  const [errorMessage, setErrorMessage] = useState('');

  useEffect(() => {
    (async () => {
      const node = await davinciClient.start();

      if (node.status !== 'success') {
        renderForm(node);
      } else {
        completeFlow(node);
      }
    })();
  }, []);

  const onSubmitHandler = async (event) => {
    event.preventDefault();
    setIsSubmittingForm(true);
    /**
     * We can just call `next` here and not worry about passing any arguments
     */
    const nextNode = await davinciClient.next();
    /**
     * Recursively render the form with the new state
     */
    mapRenderer(nextNode);
  };

  async function completeFlow(successNode) {
    const clientInfo = davinciClient.getClient();

    let code = '';
    let state = '';

    if (clientInfo?.status === 'success') {
      code = clientInfo.authorization?.code || '';
      state = clientInfo.authorization?.state || '';
    }

    await TokenManager.getTokens({ query: { code, state } });
    const user = await UserManager.getCurrentUser();
    methods.setUser(user.preferred_username);
    methods.setEmail(user.email);
    methods.setAuthentication(true);
    // Login flow specific callback
    flowCompleteCb();
  }

  // Update the UI with the new node
  async function renderForm(nextNode) {
    // clear form contents
    setCollectors([]);
    // Set h1 header
    setPageHeader(nextNode.client?.name || '');
    const collectors = davinciClient.getCollectors();
    // Save collectors to state
    setCollectors(collectors);
    // If node is a protect node, move to next node without user interaction
    if (davinciClient.getCollectors().find((collector) => collector.name === 'protectsdk')) {
      const nextNode = await davinciClient.next();
      mapRenderer(nextNode);
    }
  }

  function mapRenderer(nextNode) {
    setIsSubmittingForm(false);
    if (nextNode.status === 'next') {
      renderForm(nextNode);
    } else if (nextNode.status === 'success') {
      completeFlow(nextNode);
    } else if (nextNode.status === 'error') {
      setErrorMessage(nextNode.error.message);
    } else {
      console.error('Unknown node status', nextNode);
    }
  }

  return (
    <form onSubmit={onSubmitHandler}>
      {pageHeader && <h2>{pageHeader}</h2>}
      {errorMessage.length > 0 && <ErrorMessage message={errorMessage} />}
      {errorMessage.length == 0 &&
        collectors.map((collector) => {
          if (collector.type === 'TextCollector' && collector.name === 'protectsdk') {
            return (
              <Protect
                collector={collector}
                updater={davinciClient.update(collector)}
                key={`protect-${collector.output.key}`}
              />
            );
          } else if (collector.type === 'TextCollector') {
            return (
              <TextInput
                collector={collector}
                updater={davinciClient.update(collector)}
                key={`text-${collector.output.key}`}
              />
            );
          } else if (collector.type === 'PasswordCollector') {
            return (
              <Password
                collector={collector}
                updater={davinciClient.update(collector)}
                key={`password-${collector.output.key}`}
              />
            );
          } else if (collector.type === 'SubmitCollector') {
            return (
              <SubmitButton
                collector={collector}
                key={`submit-btn-${collector.output.key}`}
                submittingForm={isSubmittingForm}
              />
            );
          } else if (collector.type === 'FlowCollector') {
            return (
              <FlowButton
                collector={collector}
                key={`flow-btn-${collector.output.key}`}
                flow={davinciClient.flow({ action: collector.output.key })}
                renderForm={renderForm}
              />
            );
          }
        })}
    </form>
  );
}
