// javascript/angular-todo-davinci/src/app/features/davinci-client/error-message/error-message.component.ts
/*
 * angular-todo-prototype
 *
 * error-message.component.ts
 *
 * Copyright (c) 2021 ForgeRock. All rights reserved.
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 */

import { Component, Input } from '@angular/core';
import { AlertIconComponent } from '../../../icons/alert-icon/alert-icon.component';

@Component({
  selector: 'app-error-message',
  templateUrl: './error-message.component.html',
  standalone: true,
  imports: [AlertIconComponent],
})
export class ErrorMessageComponent {
  @Input() message: string;
}

// reactjs-todo-dv/client/components/davinci-client/error-message.js
/*
 * forgerock-sample-web-react
 *
 * error-message.js
 *
 * Copyright (c) 2021 ForgeRock. All rights reserved.
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 */
import React from 'react';
import AlertIcon from '../icons/alert-icon';

export default function ErrorMessage({ message }) {
  return (
    <p className="alert alert-danger d-flex align-items-center mt-1" role="alert">
      <AlertIcon classes="cstm_alert-icon col-1" />
      <span className="ps-2">{message}</span>
    </p>
  );
}
