// javascript/angular-todo-davinci/src/app/features/davinci-client/flow-button/flow-button.component.ts
/*
 * angular-todo-prototype
 *
 * flow-button.component.ts
 *
 * Copyright (c) 2021 ForgeRock. All rights reserved.
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 */

import { Component, EventEmitter, Input, Output } from '@angular/core';

@Component({
  selector: 'app-flow-button',
  templateUrl: './flow-button.component.html',
  standalone: true,
})
export class FlowButtonComponent {
  @Input() label = '';
  @Output() clicked = new EventEmitter<void>();
}

<!--
angular-todo-prototype

flow-button.component.html

Copyright (c) 2021 ForgeRock. All rights reserved.
This software may be modified and distributed under the terms
of the MIT license. See the LICENSE file for details.
-->
<button type="button" class="btn btn-primary w-100 flow-link mb-2" (click)="clicked.emit()">
  <span> {{ label }}</span>
</button>

// reactjs-todo-dv/client/components/davinci-client/flow-button.js
/*
 * forgerock-sample-web-react
 *
 * flow-button.js
 *
 * Copyright (c) 2021 ForgeRock. All rights reserved.
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 */
import React from 'react';

export default function FlowButton({ collector, flow, renderForm }) {

  const clickHandler = async () => {
    const node = await flow(collector.output.key);
    renderForm(node);
  };

  return (
    <button
      key={collector.output.key}
      type="button"
      className="btn btn-primary w-100 flow-link mb-2"
      onClick={clickHandler}
    >
      <span> {collector.output.label}</span>
    </button>
  );
}
