// angular-todo-dv/src/app/features/davinci-client/protect/protect.component.ts
/*
 * angular-todo-prototype
 *
 * protect.component.ts
 *
 * Copyright (c) 2021 ForgeRock. All rights reserved.
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 */

import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';

@Component({
  selector: 'app-protect',
  templateUrl: './protect.component.html',
})
export class ProtectComponent implements OnInit {
  @Input() label = '';
  @Output() protectProfile = new EventEmitter<string>();

  ngOnInit() {
    this.protectProfile.emit('fakeprofile');
  }
}

<!--
angular-todo-prototype

protect.component.html

Copyright (c) 2021 ForgeRock. All rights reserved.
This software may be modified and distributed under the terms
of the MIT license. See the LICENSE file for details.
-->
<p>{{ label }}</p>

// reactjs-todo-dv/client/components/davinci-client/protect.js
/*
 * forgerock-sample-web-react
 *
 * protect.js
 *
 * Copyright (c) 2021 ForgeRock. All rights reserved.
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 */
import React from 'react';

export default function ({ collector, updater }) {
  updater('fakeprofile');
  return <p key={collector.output.key}>{collector.output.label}</p>;
}
