// javascript/angular-todo-davinci/src/app/features/davinci-client/submit-button/submit-button.component.ts
/*
 * angular-todo-prototype
 *
 * submit-button.component.ts
 *
 * Copyright (c) 2021 ForgeRock. All rights reserved.
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 */

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-submit-button',
  templateUrl: './submit-button.component.html',
  standalone: true,
  imports: [],
})
export class SubmitButtonComponent {
  @Input() key: string;
  @Input() label: string;
  @Input() submittingForm: boolean;
}

<!--
angular-todo-prototype

submit-button.component.html

Copyright (c) 2021 ForgeRock. All rights reserved.
This software may be modified and distributed under the terms
of the MIT license. See the LICENSE file for details.
-->
<button
  type="submit"
  class="btn btn-primary w-100 mb-2"
  [value]="key"
  [disabled]="submittingForm ? 'disabled' : null"
>
  @if (submittingForm) {
    <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
  }
  <span>{{ label }}</span>
</button>

// reactjs-todo-dv/client/components/davinci-client/submit-button.js
/*
 * forgerock-sample-web-react
 *
 * submit-button.js
 *
 * Copyright (c) 2021 ForgeRock. All rights reserved.
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 */
import React from 'react';

export default function SubmitButton({ collector, submittingForm }) {
  return (
    <button
      type="submit"
      className="btn btn-primary w-100 mb-2"
      value={collector.output.key}
      key={collector.output.key}
      disabled={submittingForm ? 'disabled' : null}
    >
      {
        /**
         * Render a small spinner during submission calls
         */
        submittingForm ? (
          <span
            className="spinner-border spinner-border-sm"
            role="status"
            aria-hidden="true"
          ></span>
        ) : null
      }
      <span>{collector.output.label}</span>
    </button>
  );
}
