// javascript/react-journey/client/components/journey/alert.js
/*
 * ping-sample-web-react-journey
 *
 * alert.js
 *
 * Copyright (c) 2026 Ping Identity Corporation. All rights reserved.
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 */

import React from 'react';

import AlertIcon from '../icons/alert-icon';
import VerifiedIcon from '../icons/verified-icon';

/**
 * @function Alert - React component used for displaying form errors
 * @param {Object} props - React props object passed from parent
 * @param {Object} props.message - error message
 * @returns {Object} - React component object
 */
export default function Alert({ message, type }) {
  if (type === 'error') {
    return (
      <p className="alert alert-danger d-flex align-items-center mt-1" role="alert">
        <AlertIcon classes="cstm_alert-icon col-1" />
        <span className="ps-2">{message}</span>
      </p>
    );
  } else if (type === 'success') {
    return (
      <p className="alert alert-success d-flex align-items-center mt-5" role="alert">
        <VerifiedIcon classes="cstm_verified-alert-icon" size="36px" />
        <span className="ps-2">{message}</span>
      </p>
    );
  } else {
    return (
      <p className="alert d-flex align-items-center mt-5" role="alert">
        <span className="ps-2">{message}</span>
      </p>
    );
  }
}

// javascript/Archived/angular-todo/src/app/features/journey/alert/alert.component.ts
/*
 * angular-todo-prototype
 *
 * alert.component.ts
 *
 * Copyright (c) 2021 - 2025 Ping Identity Corporation. All rights reserved.
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 */

import { Component, Input } from '@angular/core';

/**
 * Used for displaying for errors
 */
@Component({
  selector: 'app-alert',
  templateUrl: './alert.component.html',
})
export class AlertComponent {
  /**
   * Determines whether this is an error or success alert
   */
  @Input() type?: string;

  /**
   * The message to display
   */
  @Input() message?: string;
}
