// javascript/reactjs-todo-davinci/client/components/davinci-client/submit-button.js
/*
 * ping-sample-web-react-davinci
 *
 * submit-button.js
 *
 * Copyright (c) 2025 Ping Identity Corporation. All rights reserved.
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 */
import React from 'react';

export default function SubmitButton({ collector, isLoading }) {
  return (
    <button type="submit" className="btn btn-primary w-100 mb-2" disabled={isLoading}>
      {
        /**
         * Render a small spinner during submission calls
         */
        isLoading ? (
          <span
            className="spinner-border spinner-border-sm"
            role="status"
            aria-hidden="true"
          ></span>
        ) : null
      }
      <span>{collector.output.label}</span>
    </button>
  );
}

// angular-todo-dv/src/app/features/davinci-client/submit-button/submit-button.component.ts
/*
 * angular-todo-prototype
 *
 * submit-button.component.ts
 *
 * Copyright (c) 2021 ForgeRock. All rights reserved.
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 */

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-submit-button',
  templateUrl: './submit-button.component.html',
})
export class SubmitButtonComponent {
  @Input() key: string;
  @Input() label: string;
  @Input() submittingForm: boolean;
}

<!--
angular-todo-prototype

submit-button.component.html

Copyright (c) 2021 ForgeRock. All rights reserved.
This software may be modified and distributed under the terms
of the MIT license. See the LICENSE file for details.
-->
<button
  type="submit"
  class="btn btn-primary w-100 mb-2"
  [value]="key"
  [disabled]="submittingForm ? 'disabled' : null"
>
  <span
    *ngIf="submittingForm"
    class="spinner-border spinner-border-sm"
    role="status"
    aria-hidden="true"
  ></span>
  <span>{{ label }}</span>
</button>
