// javascript/reactjs-todo-start/client/components/journey/alert.js
/*
 * forgerock-sample-web-react
 *
 * alert.js
 *
 * Copyright (c) 2024 Ping Identity. All rights reserved.
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 */

import React from 'react';

import AlertIcon from '../icons/alert-icon';
import VerifiedIcon from '../icons/verified-icon';

/**
 * @function Alert - React component used for displaying form errors
 * @param {Object} props - React props object passed from parent
 * @param {Object} props.message - error message
 * @returns {Object} - React component object
 */
export default function Alert({ message, type }) {
  if (type === 'error') {
    return (
      <p className="alert alert-danger d-flex align-items-center mt-1" role="alert">
        <AlertIcon classes="cstm_alert-icon col-1" />
        <span className="ps-2">{message}</span>
      </p>
    );
  } else if (type === 'success') {
    return (
      <p className="alert alert-success d-flex align-items-center mt-5" role="alert">
        <VerifiedIcon classes="cstm_verified-alert-icon" size="36px" />
        <span className="ps-2">{message}</span>
      </p>
    );
  } else {
    return (
      <p className="alert d-flex align-items-center mt-5" role="alert">
        <span className="ps-2">{message}</span>
      </p>
    );
  }
}

// javascript/angular-todo-davinci/src/app/features/davinci-client/alert/alert.component.ts
/*
 * angular-todo-prototype
 *
 * alert.component.ts
 *
 * Copyright (c) 2021 ForgeRock. All rights reserved.
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 */

import { Component, Input } from '@angular/core';
import { AlertIconComponent } from '../../../icons/alert-icon/alert-icon.component';
import { VerifiedIconComponent } from '../../../icons/verified-icon/verified-icon.component';

/**
 * Used for displaying for errors
 */
@Component({
  selector: 'app-alert',
  templateUrl: './alert.component.html',
  standalone: true,
  imports: [AlertIconComponent, VerifiedIconComponent],
})
export class AlertComponent {
  /**
   * Determines whether this is an error or success alert
   */
  @Input() type?: string;

  /**
   * The message to display
   */
  @Input() message?: string;
}

<!--
angular-todo-prototype

alert.component.html

Copyright (c) 2021 ForgeRock. All rights reserved.
This software may be modified and distributed under the terms
of the MIT license. See the LICENSE file for details.
-->

<!--
Display the message in a danger or success style alert depending on the type
-->
@switch (type) {
  @case ('error') {
    <p class="alert alert-danger d-flex align-items-center mt-1" role="alert">
      <app-alert-icon></app-alert-icon>
      <span class="ps-2">{{ message }}</span>
    </p>
  }
  @case ('success') {
    <p class="alert alert-success d-flex align-items-center mt-5" role="alert">
      <app-verified-icon size="36px"></app-verified-icon>
      <span class="ps-2">{{ message }}</span>
    </p>
  }
  @default {
    <p class="alert d-flex align-items-center mt-5" role="alert">
      <span class="ps-2">{{ message }}</span>
    </p>
  }
}
