// javascript/angular-todo-davinci/src/app/views/login/login.component.ts
/*
 * ping-sample-web-angular-davinci
 *
 * login.component.ts
 *
 * Copyright (c) 2025 Ping Identity Corporation. All rights reserved.
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 */

import { Component } from '@angular/core';
import { BackHomeComponent } from '../../utilities/back-home/back-home.component';

import { DavinciFormComponent } from '../../features/davinci-client/form/form.component';

/**
 * Used to show a login page
 */
@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  standalone: true,
  imports: [BackHomeComponent, DavinciFormComponent],
})
export class LoginComponent {}

<!--
angular-todo-prototype

login.component.html

Copyright (c) 2021 ForgeRock. All rights reserved.
This software may be modified and distributed under the terms
of the MIT license. See the LICENSE file for details.
-->

<div class="cstm_container_v-centered container-fluid d-flex align-items-center">
  <div class="w-100">
    <app-back-home></app-back-home>
    <div class="card shadow-sm p-5 mb-2 w-100">
      <div class="cstm_form-icon align-self-center mb-3">
        <ng-container *ngIf="!isWebAuthn; else fingerPrint">
          <app-key-icon size="72px"></app-key-icon>
        </ng-container>
      </div>
      <app-davinci-flow (flowComplete)="onCompleteFlow()"></app-davinci-flow>
    </div>
  </div>
</div>

<ng-template #fingerPrint>
  <app-finger-print-icon size="72px"></app-finger-print-icon>
</ng-template>

// javascript/reactjs-todo-journey/client/views/login.js
/*
 * forgerock-sample-web-react
 *
 * login.js
 *
 * Copyright (c) 2024 - 2026 Ping Identity Corporation. All rights reserved.
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 */
import React, { useContext } from 'react';
import { Link, useSearchParams } from 'react-router-dom';

import BackHome from '../components/utilities/back-home';
import Card from '../components/layout/card';
import { AppContext } from '../global-state';
import Form from '../components/journey/form';

/**
 * @function Login - React view for Login
 * @returns {Object} - React component object
 */
export default function Login() {
  const [contextState] = useContext(AppContext);
  const [params] = useSearchParams();

  const journey = params.get('journey');
  return (
    <div className="cstm_container_v-centered container-fluid d-flex align-items-center">
      <div className="w-100">
        <BackHome />
        <Card>
          <Form
            action={{ type: 'login' }}
            bottomMessage={
              <p className={`text-center text-secondary p-3 ${contextState.theme.textClass}`}>
                Don’t have an account? <Link to="/register">Sign up here!</Link>
              </p>
            }
            journey={journey}
          />
        </Card>
      </div>
    </div>
  );
}
