// javascript/reactjs-todo-davinci/client/views/todos.js
/*
 * ping-sample-web-react-davinci
 *
 * todos.js
 *
 * Copyright (c) 2025 Ping Identity Corporation. All rights reserved.
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 */

import React, { useContext, Fragment, useReducer, useState } from 'react';

import { AppContext } from '../global-state';
import CreateTodo from '../components/todos/create';
import DeleteModal from '../components/todos/delete';
import EditModal from '../components/todos/edit';
import useTodoFetch from '../components/todos/fetch';
import reducer from '../components/todos/reducer';
import Todo from '../components/todos/todo';
import apiRequest from '../utilities/request';

/**
 * @function Todos - React view for retrieving & displaying todo collection
 * @returns {Object} - React component object
 */
export default function Todos() {
  /**
   * Use local, component state for todos. Though, this could be moved to
   * the global state if that's preferred over doing API calls in React views.
   * The destructing of the hook's array results in index 0 having the state value,
   * and index 1 having the "setter" method to set new state values.
   */
  const [state] = useContext(AppContext);
  const [hasFetched, setFetched] = useState(false);
  const [todos, dispatch] = useReducer(reducer, []);
  const [selectedDeleteTodo, setSelectedDeleteTodo] = useState(null);
  const [selectedEditTodo, setSelectedEditTodo] = useState(null);

  useTodoFetch(dispatch, setFetched);

  function addTodo(newTodo) {
    dispatch({ type: 'add-todo', payload: { todo: newTodo } });
  }

  async function completeTodo(_id, completed) {
    dispatch({ type: 'complete-todo', payload: { _id, completed } });
    await apiRequest(`todos/${_id}`, 'POST', { completed });
  }

  async function deleteTodo() {
    dispatch({ type: 'delete-todo', payload: { _id: selectedDeleteTodo._id } });
    await apiRequest(`todos/${selectedDeleteTodo._id}`, 'DELETE');
  }

  async function editTodo({ _id, title }) {
    dispatch({ type: 'edit-todo', payload: { _id, title } });
    await apiRequest(`todos/${_id}`, 'POST', { title });
  }

  /**
   * Dynamic React component for rendering either the loading component
   * or the Todos collection component.
   */
  const Todos = hasFetched ? (
    <ul className={`list-group list-group-flush mb-1 ${state.theme.listGroupClass}`}>
      {/**
       * We we've fetched the todos, iterate over them for display.
       * If no todos were returned, show the "no todos" message.
       */}
      {todos.length ? (
        todos.map((item) => {
          return (
            <Todo
              completeTodo={completeTodo}
              item={item}
              key={item._id}
              setSelectedDeleteTodo={setSelectedDeleteTodo}
              setSelectedEditTodo={setSelectedEditTodo}
            />
          );
        })
      ) : (
        <li className="cstm_todo-item list-group-item list-group-item-action p-0">
          <div className="row">
            <p className="col d-flex align-items-center fs-5 text-muted w-100 ms-3 p-3">
              No todos yet. Create one above!
            </p>
          </div>
        </li>
      )}
    </ul>
  ) : (
    <p
      className={`d-flex justify-content-center align-items-center border-top px-3 ${state.theme.borderClass}`}
    >
      <span className="spinner-border text-primary my-2" role="status"></span>
      <span className="p-3 fs-5">Collecting your todos ...</span>
    </p>
  );

  return (
    <Fragment>
      <div className={`cstm_container container-fluid`}>
        <h1 className={`mt-5 ${state.theme.textClass}`}>Your Todos</h1>
        <p className="fs-6 text-muted">Create and manage your todos.</p>
        <div className={`card shadow-sm mb-5 ${state.theme.cardBgClass}`}>
          <CreateTodo addTodo={addTodo} />
          {Todos}
        </div>
      </div>
      <EditModal
        editTodo={editTodo}
        selectedEditTodo={selectedEditTodo}
        setSelectedEditTodo={setSelectedEditTodo}
      />
      <DeleteModal deleteTodo={deleteTodo} setSelectedDeleteTodo={setSelectedDeleteTodo} />
    </Fragment>
  );
}

// javascript/angular-todo-davinci/src/app/views/todos/todos.component.ts
/*
 * ping-sample-web-angular-davinci
 *
 * todos.component.ts
 *
 * Copyright (c) 2025 Ping Identity Corporation. All rights reserved.
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 */

import { OnInit, inject } from '@angular/core';
import { Component } from '@angular/core';
import { Todo } from '../../features/todo/todo';
import { TodoService } from '../../services/todo.service';
import { HeaderComponent } from '../../layout/header/header.component';
import { FormsModule } from '@angular/forms';
import { TodoComponent } from '../../features/todo/todo.component';
import { FooterComponent } from '../../layout/footer/footer.component';

/**
 * Used to display a page to list Todos and allow the user to interact with them
 */
@Component({
  selector: 'app-todos',
  templateUrl: './todos.component.html',
  standalone: true,
  imports: [HeaderComponent, FormsModule, TodoComponent, FooterComponent],
})
export class TodosComponent implements OnInit {
  private readonly todoService = inject(TodoService);

  /**
   * The existing Todos
   */
  todos: Todo[] = [];

  /**
   * A new, empty Todo to be filled in by the user and submitted
   */
  newTodo: Todo = { _id: '', title: '', completed: false };

  /**
   * A Todo marked for editing
   */
  editTodo?: Todo;

  /**
   * A Todo marked for deletion
   */
  deleteTodo?: Todo;

  /**
   * Retrieve Todos on load
   */
  ngOnInit(): void {
    this.getTodos();
  }

  /**
   * Marks a given Todo to be edited using a modal
   * @param todo - The Todo to be edited
   */
  setEditTodo(todo: Todo): void {
    this.editTodo = todo;
  }

  /**
   * Marks a given Todo to be confirmed for deletion using a modal
   * @param todo - The Todo to be deleted
   */
  setDeleteTodo(todo: Todo): void {
    this.deleteTodo = todo;
  }

  /**
   * Reset all Todos and edits/deletes on the page
   */
  resetTodos(): void {
    this.editTodo = undefined;
    this.deleteTodo = undefined;
    this.newTodo = { _id: '', title: '', completed: false };
    this.getTodos();
  }

  /**
   * Retrieve Todos
   */
  async getTodos(): Promise<void> {
    try {
      const todos = await this.todoService.getTodos();
      const json = await todos.json();
      this.todos = json as Todo[];
    } catch (err) {
      console.log(err);
    }
  }

  /**
   * Submit a Todo to be created on the backend
   * @param todo - The Todo to be submitted for creation
   */
  async create(todo: Todo): Promise<void> {
    try {
      await this.todoService.createTodo(todo);
      this.resetTodos();
    } catch (err) {
      console.log(err);
    }
  }

  /**
   * Submit a Todo to be marked as complete on the backend
   * @param todo - The Todo to be submitted as complete
   */
  async complete(todo: Todo): Promise<void> {
    try {
      await this.todoService.completeTodo(todo);
      this.resetTodos();
    } catch (err) {
      console.log(err);
    }
  }

  /**
   * Submit a Todo to be updated
   * @param todo - The updated Todo to be submitted
   */
  async update(todo: Todo): Promise<void> {
    try {
      await this.todoService.updateTodo(todo);
      this.resetTodos();
    } catch (err) {
      console.log(err);
    }
  }

  /**
   * Submit a Todo to be deleted on the backend
   * @param todo - The Todo to be submitted for deletion
   */
  async delete(todo: Todo): Promise<void> {
    try {
      await this.todoService.deleteTodo(todo);
      this.resetTodos();
    } catch (err) {
      console.log(err);
    }
  }
}

<!--
angular-todo-prototype

todos.component.html

Copyright (c) 2021 ForgeRock. All rights reserved.
This software may be modified and distributed under the terms
of the MIT license. See the LICENSE file for details.
-->

<app-header></app-header>
<div class="cstm_container container-fluid">
  <h1 class="mt-5">Your Todos</h1>
  <p class="fs-6 text-muted">Create and manage your todos.</p>

  <div class="card shadow-sm mb-5">
    <!--
    Allow the user to easily create a new Todo
    -->
    <form (ngSubmit)="create(newTodo)" #newTodoForm="ngForm" class="p-3 d-flex" ngNativeValidate>
      <div class="cstm_todos-input cstm_form-floating form-floating flex-grow-1">
        <input
          id="newTodo"
          type="text"
          class="cstm_form-control form-control bg-transparent"
          placeholder="What needs doing?"
          required=""
          [(ngModel)]="newTodo.title"
          name="title"
          />
        <label for="newTodo">What needs doing?</label>
      </div>
      <button type="submit" class="btn btn-primary ms-2">Create</button>
    </form>

    <!--
    Display list of existing Todos
    -->
    <ng-container [ngTemplateOutlet]="todos.length > 0 ? todolist : empty">
      <ng-template #todolist>
        <ul class="list-group list-group-flush">
          <!--
          For each Todo observe their outputs for completed, edit or delete events.
          -->
          @for (todo of todos; track todo) {
            <app-todo
              [todo]="todo"
              (completed)="complete(todo)"
              (edit)="setEditTodo(todo)"
              (delete)="setDeleteTodo(todo)"
            ></app-todo>
          }
        </ul>

        <!--
        If a child Todo component has indicated that it is ready for editing, display a modal allowing the user to edit and submit or cancel.
        This is triggered from the Todo component using the modal ID.
        -->
        <div
          class="modal fade"
          data-bs-backdrop="static"
          id="editModal"
          tabIndex="-1"
          aria-modal="true"
          role="dialog"
          >
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h4 class="modal-title">Edit Todo</h4>
              </div>
              @if (editTodo) {
                <form class="modal-body" (ngSubmit)="update(editTodo)">
                  <div class="cstm_todos-input cstm_form-floating form-floating flex-grow-1">
                    <input
                      id="editTodo"
                      type="text"
                      class="cstm_form-control form-control bg-transparent"
                      [defaultValue]="editTodo.title"
                      [(ngModel)]="editTodo.title"
                      required="required"
                      />
                    <label for="editTodo">Update todo text</label>
                  </div>
                </form>
              }
              @if (editTodo) {
                <div class="modal-footer">
                  <button
                    id="closeEditModalBtn"
                    type="button"
                    data-bs-toggle="modal"
                    data-bs-target="#editModal"
                    class="btn btn-secondary"
                    >
                    Close
                  </button>
                  <button
                    type="button"
                    data-bs-toggle="modal"
                    data-bs-target="#editModal"
                    class="btn btn-primary"
                    (click)="update(editTodo)"
                    >
                    Update Todo
                  </button>
                </div>
              }
            </div>
          </div>
        </div>

        <!--
        If a child Todo component has indicated that it is ready for deletion, display a modal asking for confirmation that they meant to do this.
        This is triggered from the Todo component using the modal ID.
        -->
        <div
          class="modal fade"
          data-bs-backdrop="static"
          id="deleteModal"
          tabIndex="-1"
          aria-modal="true"
          role="dialog"
          >
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-body pt-4 px-4">
                <p>Are you sure you want to delete this todo?</p>
              </div>
              <div class="modal-footer p-3">
                <button
                  type="button"
                  data-bs-toggle="modal"
                  data-bs-target="#deleteModal"
                  class="btn btn-secondary"
                  >
                  Close
                </button>
                @if (deleteTodo) {
                  <button
                    type="button"
                    data-bs-toggle="modal"
                    data-bs-target="#deleteModal"
                    class="btn btn-danger"
                    (click)="delete(deleteTodo)"
                    >
                    Delete Todo
                  </button>
                }
              </div>
            </div>
          </div>
        </div>
      </ng-template>

      <!--
      No Todos to show
      -->
      <ng-template #empty>
        <ul class="list-group list-group-flush mb-1">
          <li class="cstm_todo-item list-group-item list-group-item-action p-0">
            <div class="row">
              <p class="col d-flex align-items-center fs-5 text-muted w-100 ms-3 p-3">
                No todos yet. Create one above!
              </p>
            </div>
          </li>
        </ul>
      </ng-template>
    </ng-container>
  </div>
</div>
<app-footer></app-footer>
