// javascript/reactjs-todo-start/client/components/journey/boolean.js
/*
 * forgerock-sample-web-react
 *
 * boolean.js
 *
 * Copyright (c) 2024 Ping Identity. All rights reserved.
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 */

import React from 'react';

import { DEBUGGER } from '../../constants';

/**
 * @function Boolean - React component used for displaying checkboxes
 * @param {Object} props - React props object passed from parent
 * @param {Object} props.callback - The callback object from AM
 * @returns {Object} - React component object
 */
export default function Boolean({ callback, inputName }) {
  /** *************************************************************************
   * SDK INTEGRATION POINT
   * Summary: SDK callback methods for getting values
   * --------------------------------------------------------------------------
   * Details: Each callback is wrapped by the SDK to provide helper methods
   * for accessing values from the callbacks received from AM
   ************************************************************************* */
  if (DEBUGGER) debugger;
  const prompt = callback.getPrompt();
  const value = callback.getInputValue();

  function setValue(e) {
    /** ***********************************************************************
     * SDK INTEGRATION POINT
     * Summary: SDK callback methods for setting values
     * ------------------------------------------------------------------------
     * Details: Each callback is wrapped by the SDK to provide helper methods
     * for writing values to the callbacks received from AM
     *********************************************************************** */
    if (DEBUGGER) debugger;
    callback.setInputValue(e.target.checked);
  }
  return (
    <div className="form-check mb-3">
      <input
        className="form-check-input"
        defaultChecked={value}
        id={inputName}
        onChange={setValue}
        type="checkbox"
      />
      <label htmlFor={inputName} className="form-check-label">
        {prompt}
      </label>
    </div>
  );
}

// angular-todo-dv/src/app/features/journey/boolean/boolean.component.ts
/*
 * angular-todo-prototype
 *
 * boolean.component.ts
 *
 * Copyright (c) 2021 ForgeRock. All rights reserved.
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 */

import { Component, EventEmitter, Input, Output } from '@angular/core';
import { AttributeInputCallback } from '@forgerock/javascript-sdk';

/**
 * Used to display checkboxes
 */
@Component({
  selector: 'app-boolean',
  templateUrl: './boolean.component.html',
})
export class BooleanComponent {
  /**
   * The callback to be represented as a checkbox
   */
  @Input() callback?: AttributeInputCallback<boolean>;

  /**
   * The name of the callback
   */
  @Input() name?: string;

  /**
   * Emits a boolean representing the updated state of the checkbox
   */
  @Output() updatedCallback = new EventEmitter<boolean>();

  /**
   * Emit an event to the parent component, passing the updated value of the checkbox
   * @param event - the updated value of the checkbox
   */
  updateValue(event): void {
    this.updatedCallback.emit(event.currentTarget.checked);
  }
}
