// javascript/Archived/angular-todo-davinci/src/app/views/login/login.component.ts
/*
 * ping-sample-web-angular-davinci
 *
 * login.component.ts
 *
 * Copyright (c) 2025 Ping Identity Corporation. All rights reserved.
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 */

import { Component } from '@angular/core';
import { BackHomeComponent } from '../../utilities/back-home/back-home.component';

import { DavinciFormComponent } from '../../features/davinci/form/form.component';

/**
 * Used to show a login page
 */
@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  standalone: true,
  imports: [BackHomeComponent, DavinciFormComponent],
})
export class LoginComponent {}

// javascript/reactjs-todo-davinci/client/views/login.js
/*
 * ping-sample-web-react-davinci
 *
 * login.js
 *
 * Copyright (c) 2025 - 2026 Ping Identity Corporation. All rights reserved.
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 */
import React from 'react';
import BackHome from '../components/utilities/back-home.js';
import Card from '../components/layout/card.js';
import Form from '../components/davinci-client/form.js';

/**
 * @function Login - React view for Login
 * @returns {Object} - React component object
 */
export default function Login() {
  return (
    <div className="cstm_container_v-centered container-fluid d-flex align-items-center">
      <div className="w-100">
        <BackHome />
        <Card>
          <Form />
        </Card>
      </div>
    </div>
  );
}
