// javascript/angular-todo-davinci/src/app/features/davinci-client/unknown/unknown.component.ts
/*
 * angular-todo-prototype
 *
 * unknown.component.ts
 *
 * Copyright (c) 2021 ForgeRock. All rights reserved.
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 */

import { Component, Input } from '@angular/core';
import { Collectors } from '@forgerock/davinci-client/types';

/**
 * Used to display a message if there is an unknown callback
 */
@Component({
  selector: 'app-unknown',
  templateUrl: './unknown.component.html',
  standalone: true,
})
export class UnknownComponent {
  /**
   * The callback that is of an unknown type
   */
  @Input() collector?: Collectors;
}

<!--
angular-todo-prototype

unknown.component.html

Copyright (c) 2021 ForgeRock. All rights reserved.
This software may be modified and distributed under the terms
of the MIT license. See the LICENSE file for details.
-->

<div class="form-group">
  <p>Warning: unknown collector type, {{ collector?.type }}, isn't handled</p>
</div>

// javascript/reactjs-todo-start/client/components/journey/unknown.js
/*
 * forgerock-sample-web-react
 *
 * unknown.js
 *
 * Copyright (c) 2024 Ping Identity. All rights reserved.
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 */

import React from 'react';

/**
 * @function Unknown- React component used for displaying Unknown callback
 * @returns {Object} - React component object
 */
export default function Unknown({ callback }) {
  const callbackType = callback.getType();

  return (
    <div className="form-group">
      <p>{`Warning: unknown callback type, ${callbackType}, isn't handled`}</p>
    </div>
  );
}
