// javascript/react-journey/client/components/journey/button.jsx
/*
 * ping-sample-web-react-journey
 *
 * button.js
 *
 * Copyright (c) 2026 Ping Identity Corporation. All rights reserved.
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 */

export default function Button({ buttonText, submittingForm }) {
  return (
    <button
      type="submit"
      className="btn btn-primary w-100"
      disabled={submittingForm ? 'disabled' : null}
    >
      {
        /**
         * Render a small spinner during submission calls
         */
        submittingForm ? (
          <span
            className="spinner-border spinner-border-sm"
            role="status"
            aria-hidden="true"
          ></span>
        ) : null
      }
      <span> {buttonText}</span>
    </button>
  );
}

// javascript/angular-todo/src/app/features/journey/button/button.component.ts
/*
 * angular-todo-prototype
 *
 * button.component.ts
 *
 * Copyright (c) 2021 - 2025 Ping Identity Corporation. All rights reserved.
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 */

import { Component, Input } from '@angular/core';

/**
 * Displays a button to submit the form
 */
@Component({
  selector: 'app-button',
  templateUrl: './button.component.html',
})
export class ButtonComponent {
  /**
   * The text to be displayed on the button
   */
  @Input() buttonText?: string;

  /**
   * Whether the form is currently being submitted and a spinner should be displayed
   */
  @Input() submittingForm?: boolean;
}

<!--
angular-todo-prototype

button.component.html

Copyright (c) 2021 - 2025 Ping Identity Corporation. All rights reserved.
This software may be modified and distributed under the terms
of the MIT license. See the LICENSE file for details.
-->

<button type="submit" class="btn btn-primary w-100" [disabled]="submittingForm ? 'disabled' : null">
  <!--
    Render a small spinner during submission calls
  -->
  <span
    *ngIf="submittingForm"
    class="spinner-border spinner-border-sm"
    role="status"
    aria-hidden="true"
  ></span>
  <span> {{ buttonText }}</span>
</button>
