// archived/javascript/angular-todo/src/app/features/journey/textOutput/textOutput.component.ts
/*
 * angular-todo-prototype
 *
 * textOutput.component.ts
 *
 * Copyright (c) 2021 - 2025 Ping Identity Corporation. All rights reserved.
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 */

import { Component } from '@angular/core';
@Component({
  // eslint-disable-next-line @angular-eslint/component-selector
  selector: 'app-textOutput',
  templateUrl: './textOutput.component.html',
})
export class TextOutputComponent {}

// javascript/reactjs-todo-journey/client/components/journey/text-output.jsx
/*
 * ping-sample-web-react-journey
 *
 * textOutput.js
 *
 * Copyright (c) 2026 Ping Identity Corporation. All rights reserved.
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 */
/**
 * @function TextOutput- React component used for displaying text Outputcallback
 * @param {Object} props - React props object passed from parent
 * @returns {Object} - React component object
 */

/** 
 component added to render purposes, at this point this callback renders no element
*/

export default function TextOutput({ callback }) {
  const existingValue = callback.getMessage();
  return <p> {existingValue} </p>;
}
