// reactjs-todo/client/views/login.js
/*
 * forgerock-sample-web-react
 *
 * login.js
 *
 * Copyright (c) 2021 ForgeRock. All rights reserved.
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 */
import React, { useContext, useEffect, useState } from 'react';
import { Link, useSearchParams, useNavigate } from 'react-router-dom';

import BackHome from '../components/utilities/back-home';
import Loading from '../components/utilities/loading';
import Card from '../components/layout/card';
import { AppContext } from '../global-state';
import Form from '../components/journey/form';

import { CENTRALIZED_LOGIN } from '../constants';

import { TokenManager, UserManager } from '@forgerock/javascript-sdk';

/**
 * @function Login - React view for Login
 * @returns {Object} - React component object
 */
export default function Login() {
  // Used for setting global authentication state
  const [contextState, methods] = useContext(AppContext);

  // Used for redirection after success
  const navigate = useNavigate();
  const [params] = useSearchParams();

  // Get the code and state from the URL query parameters
  const codeParam = params.get('code');
  const errorParam = params.get('error');
  const stateParam = params.get('state');
  const centralLogin = params.get('centralLogin');
  const journey = params.get('journey');

  // Get environment variable
  const isCentralizedLogin = CENTRALIZED_LOGIN === 'true' || centralLogin === 'true';
  const [state, setState] = useState({
    loadingMessage: '',
  });

  useEffect(() => {
    async function checkCentralizedLogin() {
      if (isCentralizedLogin) {
        if (codeParam && stateParam) {
          /** *****************************************************************
           * SDK INTEGRATION POINT
           * Summary: Get OAuth/OIDC tokens with Authorization Code Flow w/PKCE.
           * ------------------------------------------------------------------
           * Details:When the user return to this app after successfully logging in,
           * the URL will include code and state query parameters that need to
           * be passed in to complete the OAuth flow giving the user access
           ***************************************************************** */
          setState({
            loadingMessage: 'Success! Redirecting ...',
          });
          await authorize(codeParam, stateParam);
        } else if (errorParam) {
          // Do nothing as it will redirect for central login
        } else {
          /** *****************************************************************
           * SDK INTEGRATION POINT
           * Summary: Get OAuth/OIDC tokens with Authorization Code Flow w/PKCE.
           * ------------------------------------------------------------------
           * The key-value of `login: redirect` is what allows central-login.
           * Passing no arguments or a key-value of `login: 'embedded'` means
           * the app handles authentication locally
           ***************************************************************** */
          setState({
            loadingMessage: 'Redirecting ...',
          });
          await TokenManager.getTokens({ login: 'redirect', query: { acr_values: 'simpleLogin' } });
        }
      }
    }
    checkCentralizedLogin();
  }, []);

  async function authorize(codeParam, stateParam) {
    await TokenManager.getTokens({ query: { codeParam, stateParam } });
    const user = await UserManager.getCurrentUser();
    methods.setUser(user.name);
    methods.setEmail(user.email);
    methods.setAuthentication(true);
    navigate('/');
  }

  if (!isCentralizedLogin) {
    return (
      <div className="cstm_container_v-centered container-fluid d-flex align-items-center">
        <div className="w-100">
          <BackHome />
          <Card>
            <Form
              action={{ type: 'login' }}
              bottomMessage={
                <p className={`text-center text-secondary p-3 ${contextState.theme.textClass}`}>
                  Don’t have an account? <Link to="/register">Sign up here!</Link>
                </p>
              }
              journey={journey}
            />
          </Card>
        </div>
      </div>
    );
  } else {
    return (
      <div className="cstm_container_v-centered container-fluid d-flex align-items-center">
        <div className="w-100">
          <Loading message={state.loadingMessage} />
        </div>
      </div>
    );
  }
}

// angular-todo-dv/src/app/views/login/login.component.ts
/*
 * angular-todo-prototype
 *
 * login.component.ts
 *
 * Copyright (c) 2021 ForgeRock. All rights reserved.
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 */

import { Component, OnInit } from '@angular/core';
import { environment } from '../../../environments/environment';
import { TokenManager, UserManager } from '@forgerock/javascript-sdk';
import { ActivatedRoute, Router } from '@angular/router';
import { UserService } from '../../services/user.service';

/**
 * Used to show a login page
 */
@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
})
export class LoginComponent implements OnInit {
  isWebAuthn = false;
  code: string;
  error: string;
  state: string;
  centralLogin: string;
  loadingMessage: string;
  journey: string;

  get isCentralizedLogin(): boolean {
    return this.centralLogin === 'true' || environment.CENTRALIZED_LOGIN === 'true' ? true : false;
  }

  constructor(
    private route: ActivatedRoute,
    public userService: UserService,
    private router: Router,
  ) {}

  async ngOnInit(): Promise<void> {
    this.code = this.route.snapshot.queryParamMap.get('code');
    this.error = this.route.snapshot.queryParamMap.get('error');
    this.state = this.route.snapshot.queryParamMap.get('state');
    this.centralLogin = this.route.snapshot.queryParamMap.get('centralLogin');
    this.journey = this.route.snapshot.queryParamMap.get('journey');

    if (this.isCentralizedLogin) {
      if (this.code && this.state) {
        /** *****************************************************************
         * SDK INTEGRATION POINT
         * Summary: Get OAuth/OIDC tokens with Authorization Code Flow w/PKCE.
         * ------------------------------------------------------------------
         * Details:When the user return to this app after successfully logging in,
         * the URL will include code and state query parameters that need to
         * be passed in to complete the OAuth flow giving the user access
         ***************************************************************** */
        this.loadingMessage = 'Success! Redirecting ...';
        await this.authorize(this.code, this.state);
      } else if (this.error) {
        // Do nothing as this will result in a redirect
      } else {
        /** *****************************************************************
         * SDK INTEGRATION POINT
         * Summary: Get OAuth/OIDC tokens with Authorization Code Flow w/PKCE.
         * ------------------------------------------------------------------
         * The key-value of `login: redirect` is what allows central-login.
         * Passing no arguments or a key-value of `login: 'embedded'` means
         * the app handles authentication locally
         ***************************************************************** */
        this.loadingMessage = 'Redirecting ...';
        await TokenManager.getTokens({ login: 'redirect', query: { acr_values: 'simpleLogin' } });
      }
    }
  }

  onSetIsWebAuthn(isWebAuthn: boolean): void {
    this.isWebAuthn = isWebAuthn;
  }

  async authorize(code: string, state: string): Promise<void> {
    await TokenManager.getTokens({ query: { code, state } });
    const user = (await UserManager.getCurrentUser()) as Record<string, unknown>;
    this.userService.info = user;
    this.userService.isAuthenticated = true;
    this.router.navigateByUrl('/');
  }
}

<!--
angular-todo-prototype

login.component.html

Copyright (c) 2021 ForgeRock. All rights reserved.
This software may be modified and distributed under the terms
of the MIT license. See the LICENSE file for details.
-->

<ng-container *ngIf="!isCentralizedLogin; else loading">
  <div class="cstm_container_v-centered container-fluid d-flex align-items-center">
    <div class="w-100">
      <app-back-home></app-back-home>
      <div class="card shadow-sm p-5 mb-2 w-100">
        <div class="cstm_form-icon align-self-center mb-3">
          <ng-container *ngIf="!isWebAuthn; else fingerPrint">
            <app-key-icon size="72px"></app-key-icon>
          </ng-container>
        </div>

        <app-form
          [action]="'login'"
          [journey]="journey"
          (isWebAuthn)="onSetIsWebAuthn($event)"
        ></app-form>

        <p class="text-center text-secondary p-3">
          Don’t have an account?
          <a [routerLink]="'/register'">Sign up here!</a>
        </p>
      </div>
    </div>
  </div>
</ng-container>

<ng-template #loading>
  <div class="cstm_container_v-centered container-fluid d-flex align-items-center">
    <div class="w-100">
      <app-loading [message]="loadingMessage"></app-loading>
    </div>
  </div>
</ng-template>

<ng-template #fingerPrint>
  <app-finger-print-icon size="72px"></app-finger-print-icon>
</ng-template>
