// javascript/reactjs-todo-davinci/client/components/utilities/loading.js
/*
 * ping-sample-web-react-davinci
 *
 * loading.js
 *
 * Copyright (c) 2025 - 2026 Ping Identity Corporation. All rights reserved.
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 */

import React, { useContext } from 'react';

import { ThemeContext } from '../../context/theme.context.js';

/**
 * @function Loading - Used to display a loading message
 * @param {Object} props - The object representing React's props
 * @param {string} props.message - The message string object passed from the parent component
 * @returns {Object} - React component object
 */
export default function Loading({ classes, message }) {
  const theme = useContext(ThemeContext);
  return (
    <div className="container">
      <p className={classes}>
        <span className="d-flex justify-content-center my-2">
          <span className="cstm_loading-spinner spinner-border text-primary" role="status"></span>
        </span>
        <span className={`d-flex justify-content-center p-3 fs-5 ${theme.textClass}`}>
          {message}
        </span>
      </p>
    </div>
  );
}

// javascript/Archived/angular-todo-davinci/src/app/utilities/loading/loading.component.ts
/*
 * ping-sample-web-angular-davinci
 *
 * loading.component.ts
 *
 * Copyright (c) 2025 Ping Identity Corporation. All rights reserved.
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 */

import { Component, Input } from '@angular/core';

/**
 * Used to show a spinner and message during loading / processing steps
 */
@Component({
  selector: 'app-loading',
  templateUrl: './loading.component.html',
  standalone: true,
})
export class LoadingComponent {
  /**
   * The header to be displayed with the spinner
   */
  @Input() header?: string;
  /**
   * The message to be displayed with the spinner
   */
  @Input() message?: string;
}
